Removed hardcoded references to openoffice.org3 and tika-app-0.9.jar (refs #4334)(refs #4341)
The path to openoffice.org directory and to tika-app.jar file must be set
manually when creating `etc/te.conf` from `etc/te.conf.sample`.

diff --git a/bin/ted b/bin/ted
--- a/bin/ted
+++ b/bin/ted
@@ -53,11 +53,6 @@ REQUEST_DIRECTORY=/var/tmp
 RENDERING_MAX_CLIENT=10
 RENDERING_DIRECTORY=/var/tmp
 TE_SERVER_USER=root
-TE_OOO_BASE_DIR=/opt/openoffice.org3
-TE_OOO_SERVER_ENABLED=yes
-TE_OOO_SERVER_SOFFICE=${TE_OOO_BASE_DIR}/program/soffice
-TE_OOO_SERVER_HOST=127.0.0.1
-TE_OOO_SERVER_PORT=8123
 
 check_environment() {
     if [ ! -d "$TE_HOME" ]; then
@@ -90,10 +85,14 @@ check_environment() {
 	    echo "Error: TE_OOO_SERVER_UNOPKG '$TE_OOO_SERVER_UNOPKG' (in '$TE_HOME/etc/te.conf') is not executable!"
 	    exit 1
 	fi
-	if [ -z "(which java)" ]; then
+	if [ -z "$(which java)" ]; then
 	    echo "Error: java interpreter not found in PATH!"
 	    exit 1
 	fi
+    fi
+    if [ ! -f "$TIKA_APP_JAR" ]; then
+	echo "Error: TIKA_APP_JAR '$TIKA_APP_JAR' (in '$TE_HOME/etc/te.conf') does not exists!"
+	exit 1
     fi
 }
 
