Removed Python/UNO scripts and added Java/UNO script (closes #258)
The Java/UNO API seems more stable and less prone to segmentation faults.
Also added a new engine `ooo2doc'.

diff --git a/bin/ted b/bin/ted
--- a/bin/ted
+++ b/bin/ted
@@ -51,8 +51,9 @@ REQUEST_DIRECTORY=/var/tmp
 RENDERING_MAX_CLIENT=10
 RENDERING_DIRECTORY=/var/tmp
 TE_SERVER_USER=root
+TE_OOO_BASE_DIR=/opt/openoffice.org3
 TE_OOO_SERVER_ENABLED=yes
-TE_OOO_SERVER_SOFFICE=/opt/openoffice.org3/program/soffice
+TE_OOO_SERVER_SOFFICE=${TE_OOO_BASE_DIR}/program/soffice
 TE_OOO_SERVER_HOST=127.0.0.1
 TE_OOO_SERVER_PORT=8123
 
@@ -75,6 +76,10 @@ check_environment() {
 	exit 1
     fi
     if [ "$TE_OOO_SERVER_ENABLED" = "yes" ]; then
+	if [ ! -d "$TE_OOO_BASE_DIR" ]; then
+	    echo "Error: TE_OOO_BASE_DIR '$TE_OOO_BASE_DIR' (in '$TE_HOME/etc/te.conf') is not a directory!"
+	    exit 1
+	fi
 	if [ ! -x "$TE_OOO_SERVER_PYTHON" ]; then
 	    echo "Error: TE_OOO_SERVER_PYTHON '$TE_OOO_SERVER_PYTHON' (in '$TE_HOME/etc/te.conf') is not executable!"
 	    exit 1
@@ -85,6 +90,10 @@ check_environment() {
 	fi
 	if [ ! -x "$TE_OOO_SERVER_UNOPKG" ]; then
 	    echo "Error: TE_OOO_SERVER_UNOPKG '$TE_OOO_SERVER_UNOPKG' (in '$TE_HOME/etc/te.conf') is not executable!"
+	    exit 1
+	fi
+	if [ -z "(which java)" ]; then
+	    echo "Error: java interpreter not found in PATH!"
 	    exit 1
 	fi
     fi
