fix(test): Correct engine error reporting in test scripts (refs #4656)

diff --git a/test-data/test_html2odt b/test-data/test_html2odt
--- a/test-data/test_html2odt
+++ b/test-data/test_html2odt
@@ -20,6 +20,11 @@ TESTOUT=`mktemp_out test.html .odt`
 echo
 echo "* Checking conversion from HTML to ODT..."
 "$TE_HOME"/lib/engines/html2odt "$TESTIN" "$TESTOUT"
+RET=$?
+if [ $RET -ne 0 ]; then
+    echo "Engine exited with error code '$RET'!"
+    exit $RET
+fi
 SIZE=`stat -c %s "$TESTOUT" 2> /dev/null`
 
 if [ ! -f "$TESTOUT" -o "$SIZE" = "0" ]; then
diff --git a/test-data/test_mergeodt b/test-data/test_mergeodt
--- a/test-data/test_mergeodt
+++ b/test-data/test_mergeodt
@@ -20,6 +20,11 @@ TESTOUT=`mktemp_out test.mergeodt.zip .odt`
 echo 
 echo "* Checking conversion from ZIP to ODT..."
 "$TE_HOME"/lib/engines/zip2star odt "$TESTIN" "$TESTOUT"
+RET=$?
+if [ $RET -ne 0 ]; then
+    echo "Engine exited with error code '$RET'!"
+    exit $RET
+fi
 SIZE=`stat -c %s "$TESTOUT" 2> /dev/null`
 
 if [ ! -f "$TESTOUT" -o "$SIZE" = "0" ]; then
diff --git a/test-data/test_mergepdfa b/test-data/test_mergepdfa
--- a/test-data/test_mergepdfa
+++ b/test-data/test_mergepdfa
@@ -20,6 +20,11 @@ TESTOUT=`mktemp_out test.mergepdfa.zip .pdfa`
 echo 
 echo "* Checking conversion from ZIP to PDF/A..."
 "$TE_HOME"/lib/engines/zip2star pdfa "$TESTIN" "$TESTOUT"
+RET=$?
+if [ $RET -ne 0 ]; then
+    echo "Engine exited with error code '$RET'!"
+    exit $RET
+fi
 SIZE=`stat -c %s "$TESTOUT" 2> /dev/null`
 
 if [ ! -f "$TESTOUT" -o "$SIZE" = "0" ]; then
diff --git a/test-data/test_pdf2txt b/test-data/test_pdf2txt
--- a/test-data/test_pdf2txt
+++ b/test-data/test_pdf2txt
@@ -20,6 +20,11 @@ TESTOUT=`mktemp_out test.pdf .txt`
 echo
 echo "* Checking conversion from PDF to TXT..."
 "$TE_HOME"/lib/engines/tika2txt "$TESTIN" "$TESTOUT"
+RET=$?
+if [ $RET -ne 0 ]; then
+    echo "Engine exited with error code '$RET'!"
+    exit $RET
+fi
 SIZE=`stat -c %s "$TESTOUT" 2> /dev/null`
 
 if [ ! -f "$TESTOUT" -o "$SIZE" = "0" ]; then
diff --git a/test-data/test_pptx2pdf b/test-data/test_pptx2pdf
--- a/test-data/test_pptx2pdf
+++ b/test-data/test_pptx2pdf
@@ -20,6 +20,11 @@ TESTOUT=`mktemp_out test.ppt .pdf`
 echo
 echo "* Checking conversion from MS-PowerPoint 2007 Open XML to PDF..."
 "$TE_HOME"/lib/engines/ooo2pdf "$TESTIN" "$TESTOUT"
+RET=$?
+if [ $RET -ne 0 ]; then
+    echo "Engine exited with error code '$RET'!"
+    exit $RET
+fi
 SIZE=`stat -c %s "$TESTOUT" 2> /dev/null`
 
 if [ ! -f "$TESTOUT" -o "$SIZE" = "0" ]; then
diff --git a/test-data/test_txtlat12pdf b/test-data/test_txtlat12pdf
--- a/test-data/test_txtlat12pdf
+++ b/test-data/test_txtlat12pdf
@@ -20,6 +20,11 @@ TESTOUT=`mktemp_out test.lat1.txt .pdf`
 echo
 echo "* Checking conversion from Latin1 TXT to PDF..."
 "$TE_HOME"/lib/engines/txt2pdf "$TESTIN" "$TESTOUT"
+RET=$?
+if [ $RET -ne 0 ]; then
+    echo "Engine exited with error code '$RET'!"
+    exit $RET
+fi
 SIZE=`stat -c %s "$TESTOUT" 2> /dev/null`
 
 if [ ! -f "$TESTOUT" -o "$SIZE" = "0" ]; then
