Added mergeodt and mergepdfa to engines-check.sh

diff --git a/lib/engines/zip2star b/lib/engines/zip2star
--- a/lib/engines/zip2star
+++ b/lib/engines/zip2star
@@ -19,15 +19,18 @@ TE_OOO_SERVER_PORT=8123
 [ -f "$TE_HOME"/etc/te.d/env ] && . "$TE_HOME"/etc/te.d/env
 
 ODTW=`mktemp -td odf.XXXXXX`
-unzip $2 -d $ODTW
+unzip -qq "$2" -d "$ODTW"
 RET=$?
 if [ $RET -ne 0 ]; then
     echo "Error unpacking '$2' in '$ODTW'!"
     exit $RET
 fi
 
-find $ODTW  -type f -print0 | sort | xargs -0 "$TE_OOO_SERVER_PYTHON" "$TE_HOME/lib/engines/ooo-server-merge.py"  -o "$3" -t $1 -i
+find "$ODTW"  -type f -print0 | sort | xargs -0 "$TE_OOO_SERVER_PYTHON" "$TE_HOME/lib/engines/ooo-server-merge.py"  -o "$3" -t "$1" -i
+RET=$?
+if [ $RET -ne 0 ]; then
+    echo "Error merging '$2' to '$3'!"
+    exit $RET
+fi
 
-
-
-#/bin/rm -fr "$ODTW"
+rm -rf "$ODTW"
